version: "2"
services:
    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        restart: always
        ports:
            - 8989:8989
        volumes:
            - $HOME/.config/sonarr:/config
            - /mnt/WD-1/downloads:/downloads
            - /mnt/Seagate-1/media/tv_shows:/tv_shows
            - /mnt/Seagate-1/media/anime:/anime
        environment:
            - PGID=1001
            - PUID=1001
            - TZ=Asia/Karachi

    radarr:
        image: linuxserver/radarr
        container_name: radarr
        restart: always
        ports:
            - 7878:7878
        volumes:
            - $HOME/.config/radarr:/config
            - /mnt/WD-1/downloads:/downloads
            - /mnt/Seagate-1/media/movies:/movies
        environment:
            - PGID=1001
            - PUID=1001
            - TZ=Asia/Karachi

    jackett:
        image: linuxserver/jackett
        container_name: jackett
        restart: always
        ports:
            - 9117:9117
        volumes:
            - $HOME/.config/jackett:/config
        environment:
            - PGID=1001
            - PUID=1001
            - TZ=Asia/Karachi

    plex:
        image: linuxserver/plex
        container_name: plex
        restart: always
        network_mode: "host"
        volumes:
            - $HOME/.config/plex:/config
            - /mnt/Seagate-1/media:/media
        environment:
            - PGID=1001
            - PUID=1001
            - TZ=Asia/Karachi
            - VERSION=latest

    serviio:
        image: lsiocommunity/serviio
        container_name: serviio
        restart: always
        network_mode: "host"
        volumes:
            - $HOME/.config/serviio:/config
            - /mnt/Seagate-1/media:/media
            - /etc/localtime:/etc/localtime:ro
        environment:
            - PGID=1001
            - PUID=1001

    transmission:
        image: linuxserver/transmission
        container_name: transmission
        restart: always
        ports:
            - 9091:9091
            - 51413:51413
        volumes:
            - $HOME/.config/transmission:/config
            - /mnt/WD-1/downloads:/downloads
        environment:
            - PGID=1001
            - PUID=1001
            - TZ=Asia/Karachi

