version: "2"
services:
    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        restart: always
        ports:
            - 8989:8989
        volumes:
            - $HOME/.config/sonarr:/config
            - /mnt/WD-1/downloads:/downloads
            - /mnt/Seagate-1/media:/media
        environment:
            - PGID=1001
            - PUID=1001
            - TZ=Asia/Karachi

    transmission:
        image: linuxserver/transmission
        container_name: transmission
        restart: always
        ports:
            - 9091:9091
            - 51413:51413
        volumes:
            - $HOME/.config/transmission:/config
            - /mnt/WD-1/downloads:/downloads
        environment:
            - PGID=1001
            - PUID=1001
            - TZ=Asia/Karachi

